In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('/content/drive/MyDrive/df_4_plus_전처리.csv')
df.head()

,가게,맛,양,날짜,주문,사용자id,리뷰
0,후라이드참잘하는집-서강대점,5,5,2023-02-19,핫간장치킨（무＋소스＋콜라）,st,주문해놓고 샤워하고 나왔는데 바로 왔음 배달은 항상 빨라서 좋고 맛은 말할거 없이 ...
1,후라이드참잘하는집-서강대점,5,5,2023-02-18,순살 후라이드,yh,맛있어요 너무 맛ㅇㅅ어옿
2,후라이드참잘하는집-서강대점,5,5,2023-02-17,반마리（순살）,id,너무 맛있게 잘 먹렀어요. 머스터드 소스 넉넉히 주셔수 모자라지 않게 잘 먹었습니다.
3,후라이드참잘하는집-서강대점,5,5,2023-02-16,반마리（순살）,rl,굳굳굳 잘 먹었습니당
4,후라이드참잘하는집-서강대점,5,5,2023-02-16,핫토스치킨（뼈）（무＋소스＋콜라）,st,시즈닝 팍팍~넘 맛있었요 간만에 치킨 먹은건데 기분좋게 먹었어요

**데이터 전처리**

In [4]:
# 결측치 확인
df.isnull().sum()

가게         0
맛          0
양          0
날짜         0
주문       403
사용자id      0
리뷰         2
dtype: int64

In [5]:
df[df['주문'].isnull()]

,가게,맛,양,날짜,주문,사용자id,리뷰
59,후라이드참잘하는집-서강대점,5,5,2023-01-15,NaN,eh,"서강대점 평점이 4.8? 이건 못참지~ 5점으로 혼내드립니다~ 최고의 바삭함, 안에..."
173,후라이드참잘하는집-서강대점,5,5,2022-09-29,NaN,hy,맛있게먹었습미당항상
208,후라이드참잘하는집-서강대점,5,5,2022-09-14,NaN,kj,맛있게 잘 먹었습니다
223,후라이드참잘하는집-서강대점,5,5,2022-09-05,NaN,st,후라이드도 맛있지만 양념도 맛있어요 양념은 후참에서만 주문함ㅋㅋ양념이 바닥에 넘천 ...
265,후라이드참잘하는집-서강대점,5,5,2022-08-14,NaN,se,숭배합니다 GOAT
...,...,...,...,...,...,...,...
13346,치킨시대-명지대점,5,5,2022-02-18,NaN,pk,닭이 엄청 크네요! 치킨 샐러드 치즈볼 다 맛있게 먹었어요~ 다음에도 여기서 시킬 ...
13362,치킨시대-명지대점,5,5,2022-01-17,NaN,br,야채랑 치킨이랑 전부 너무 맛있었어요 ㅠㅠㅠㅠ 익스프레스인데도 배달 시작하고 35분...
13371,치킨시대-명지대점,5,5,2022-01-03,NaN,ki,빠른 배달 좋네요 치킨도 맛있구요 치킨무 2개 인데 1개만 왔어요 ㅋㅋ 다음에도 주...
13373,치킨시대-명지대점,5,5,2022-01-02,NaN,ng,너무너무 맛나요 진짜 치킨이 실~ 하고 양념도 너무 맛있어요 후라이드 육즙이 살아 ...
13376,치킨시대-명지대점,5,5,2021-12-23,NaN,hy,처음시켜보았는데 맛있네요 치즈볼도 정말 맛있었어요 하트야채도 감동이에요

In [6]:
df[df['리뷰'].isnull()]

                   가게  맛  양          날짜  주문 사용자id   리뷰
7673  피자와치킨의러브레터-서대문점  5  5  2022-06-11  \t    ha  NaN
8126        페리카나-합정동점  5  5  2022-05-24  \t    tl  NaN

In [7]:
# 결측치있는 행 삭제
df=df.dropna(axis=0)

In [8]:
# '총점' 추가 -> 통계 추천시스템, 가설 확인에 횔용

df['총점']=df['맛']+df['양']

In [9]:
print(len(df.loc[df['총점'] == 10]))
print(len(df.loc[df['총점'] == 9]))
print(len(df.loc[df['총점'] == 8]))
print(len(df.loc[df['총점'] == 7]))
print(len(df.loc[df['총점'] == 6]))
print(len(df.loc[df['총점'] == 5]))
print(len(df.loc[df['총점'] == 4]))
print(len(df.loc[df['총점'] == 3]))
print(len(df.loc[df['총점'] == 2]))

11793
513
357
97
93
33
34
8
49

In [10]:
# 잘못된 리뷰 삭제
df[df['주문']=='\t']

,가게,맛,양,날짜,주문,사용자id,리뷰,총점
40,후라이드참잘하는집-서강대점,5,5,2023-01-25,\t,kk,\n반반치킨（후라이드반＋양념반）/1,10
102,후라이드참잘하는집-서강대점,5,5,2022-12-16,\t,le,"\n순살 후라이드/1,반반치킨（양념반＋간장반）/1(콜라1.25L로변경(콜라1.25L...",10
104,후라이드참잘하는집-서강대점,5,5,2022-12-10,\t,ki,\n순살반반치킨（후라이드반＋양념반）/1(추가 선택(감자튀김)),10
123,후라이드참잘하는집-서강대점,5,5,2022-11-23,\t,eu,\n순살반반치킨 （후라이드반＋킹트리플반）/1(추가 선택(감자튀김)),10
236,후라이드참잘하는집-서강대점,5,5,2022-08-31,\t,ms,\n반반치킨（후라이드반＋양념반）/1,10
...,...,...,...,...,...,...,...,...
13349,치킨시대-명지대점,5,5,2022-02-14,\t,km,\n양념으로 반반/1(음료 선택(사이다500mL)),10
13352,치킨시대-명지대점,5,5,2022-02-09,\t,ng,"\n원하는대로 삼총사（반／반／반）/1(치킨선택1(크리스피（선택1）),치킨선택2(양념...",10
13360,치킨시대-명지대점,5,5,2022-01-21,\t,tm,"\n원하는대로 삼총사（반／반／반）/1(치킨선택1(크리스피（선택1）),안심순살변경추가...",10
13369,치킨시대-명지대점,5,5,2022-01-05,\t,iy,"\n원하는대로 삼총사（반／반／반）/1(치킨선택1(간장치킨（선택1）),안심순살변경추가...",10
13380,치킨시대-명지대점,5,5,2021-12-16,\t,sn,"\n크리스피치킨/1(음료 선택(콜라500mL),추가 선택(양념소스 추가,간장소스 추...",10

In [11]:
df.drop(df[df['주문']=='\t'].index, inplace=True)

**통계 추천시스템**

In [12]:
df['요일']=pd.to_datetime(df['날짜']).dt.day_name()
df['요일'].value_counts()

Sunday       2345
Saturday     2025
Monday       1788
Friday       1730
Tuesday      1600
Thursday     1595
Wednesday    1571
Name: 요일, dtype: int64

In [13]:
df2=df.groupby(['가게'], as_index=False).mean()

In [14]:
df2.sort_values(by=['총점'],ascending=False)

                   가게         맛         양        총점
44         컬투치킨-연남사랑점  4.977778  4.981481  9.959259
22    베이직프라이드치킨-신촌직영점  4.976109  4.979522  9.955631
10     굽네치킨&피자-남가좌1호점  4.968858  4.979239  9.948097
48          페리카나-홍익대점  4.967347  4.975510  9.942857
40         치킨더홈-서울이대점  4.969466  4.973282  9.942748
47          페리카나-합정동점  4.956757  4.972973  9.929730
11        굽네치킨&피자-서강점  4.966216  4.956081  9.922297
18      맘스터치피자앤치킨-연대점  4.958333  4.947917  9.906250
30           오늘통닭-신촌점  4.951311  4.921348  9.872659
45     티바두마리치킨-신수서강대점  4.957364  4.903101  9.860465
34         지코바치킨-남가좌점  4.914676  4.938567  9.853242
41          치킨시대-명지대점  4.911765  4.941176  9.852941
7    골라먹는3가지맛디디치킨-아현점  4.920139  4.930556  9.850694
36          지코바치킨-신촌점  4.938776  4.908163  9.846939
29      양념이맛있는순살킹-아현점  4.907216  4.938144  9.845361
12        굽네치킨&피자-신촌점  4.937500  4.904167  9.841667
19          맥시칸치킨-연희점  4.918728  4.922261  9.840989
39           청년치킨-서교점  4.923077  4.915751  9.838828
28              쌀통에퐁닭  4.928000  4.908000  9.836000
13       굽네치킨&피자-이대역점  4.924138  4.906897  9.831034
53     호치킨-마포래미안푸르지오점  4.917647  4.905882  9.823529
15           노랑통닭-아현점  4.915493  4.906103  9.821596
43          치킨플러스-성산점  4.889706  4.930147  9.819853
54     후라이드참잘하는집-서강대점  4.895105  4.919580  9.814685
32           자담치킨-신촌점  4.898785  4.914980  9.813765
8   골라먹는3가지맛디디치킨-연세대점  4.897727  4.912879  9.810606
37          지코바치킨-홍대점  4.894531  4.910156  9.804688
26          신미경홍대닭갈비3  4.896694  4.904959  9.801653
46           페리카나-이대점  4.889401  4.894009  9.783410
4           BHC-홍대초교점  4.878472  4.902778  9.781250
20          멕시칸치킨-연남점  4.846154  4.934066  9.780220
49            푸라닭-신수점  4.876712  4.897260  9.773973
16           롯데리아-홍대점  4.876289  4.896907  9.773196
51    피자와치킨의러브레터-서대문점  4.849593  4.918699  9.768293
42          치킨플러스-서교점  4.833935  4.931408  9.765343
23      수준이다른치킨-마포신촌점  4.877863  4.885496  9.763359
14           네네치킨-서교점  4.858779  4.889313  9.748092
3             BHC-연희점  4.866412  4.881679  9.748092
6         강정이기가막혀-연희점  4.813187  4.934066  9.747253
27         신미불닭발-서울본점  4.882129  4.855513  9.737643
5          가마로강정-광흥창점  4.854545  4.872727  9.727273
31          이나닭강정-신촌점  4.897611  4.829352  9.726962
21       바른치킨-공덕파크자이점  4.857143  4.867347  9.724490
38       처갓집양념치킨-독립문점  4.837638  4.885609  9.723247
50            푸라닭-합정점  4.866667  4.855556  9.722222
17       마깐마포깐풍기-신촌본점  4.919118  4.797794  9.716912
2             BHC-신촌점  4.855219  4.855219  9.710438
9            교촌치킨-신촌점  4.815498  4.892989  9.708487
35         지코바치킨-독립문점  4.789298  4.889632  9.678930
24        순살만공격-마포신촌점  4.825939  4.836177  9.662116
33   전국3대치킨오성통닭-마포신촌점  4.800712  4.861210  9.661922
1             BHC-공덕점  4.807560  4.828179  9.635739
0             BBQ-신촌점  4.800000  4.744444  9.544444
52      호식이두마리치킨-명지대점  4.709898  4.802048  9.511945
25       숯미남숯불치킨에미친남자  4.709302  4.697674  9.406977

**가설 확인**

1. 그냥 고민하지 말고 프랜차이즈 치킨을 시키는 것이 좋을까?

In [15]:
df2=df.groupby(['가게'], as_index=False).mean()

In [16]:
df2.sort_values(by=['총점'],ascending=False)

                   가게         맛         양        총점
44         컬투치킨-연남사랑점  4.977778  4.981481  9.959259
22    베이직프라이드치킨-신촌직영점  4.976109  4.979522  9.955631
10     굽네치킨&피자-남가좌1호점  4.968858  4.979239  9.948097
48          페리카나-홍익대점  4.967347  4.975510  9.942857
40         치킨더홈-서울이대점  4.969466  4.973282  9.942748
47          페리카나-합정동점  4.956757  4.972973  9.929730
11        굽네치킨&피자-서강점  4.966216  4.956081  9.922297
18      맘스터치피자앤치킨-연대점  4.958333  4.947917  9.906250
30           오늘통닭-신촌점  4.951311  4.921348  9.872659
45     티바두마리치킨-신수서강대점  4.957364  4.903101  9.860465
34         지코바치킨-남가좌점  4.914676  4.938567  9.853242
41          치킨시대-명지대점  4.911765  4.941176  9.852941
7    골라먹는3가지맛디디치킨-아현점  4.920139  4.930556  9.850694
36          지코바치킨-신촌점  4.938776  4.908163  9.846939
29      양념이맛있는순살킹-아현점  4.907216  4.938144  9.845361
12        굽네치킨&피자-신촌점  4.937500  4.904167  9.841667
19          맥시칸치킨-연희점  4.918728  4.922261  9.840989
39           청년치킨-서교점  4.923077  4.915751  9.838828
28              쌀통에퐁닭  4.928000  4.908000  9.836000
13       굽네치킨&피자-이대역점  4.924138  4.906897  9.831034
53     호치킨-마포래미안푸르지오점  4.917647  4.905882  9.823529
15           노랑통닭-아현점  4.915493  4.906103  9.821596
43          치킨플러스-성산점  4.889706  4.930147  9.819853
54     후라이드참잘하는집-서강대점  4.895105  4.919580  9.814685
32           자담치킨-신촌점  4.898785  4.914980  9.813765
8   골라먹는3가지맛디디치킨-연세대점  4.897727  4.912879  9.810606
37          지코바치킨-홍대점  4.894531  4.910156  9.804688
26          신미경홍대닭갈비3  4.896694  4.904959  9.801653
46           페리카나-이대점  4.889401  4.894009  9.783410
4           BHC-홍대초교점  4.878472  4.902778  9.781250
20          멕시칸치킨-연남점  4.846154  4.934066  9.780220
49            푸라닭-신수점  4.876712  4.897260  9.773973
16           롯데리아-홍대점  4.876289  4.896907  9.773196
51    피자와치킨의러브레터-서대문점  4.849593  4.918699  9.768293
42          치킨플러스-서교점  4.833935  4.931408  9.765343
23      수준이다른치킨-마포신촌점  4.877863  4.885496  9.763359
14           네네치킨-서교점  4.858779  4.889313  9.748092
3             BHC-연희점  4.866412  4.881679  9.748092
6         강정이기가막혀-연희점  4.813187  4.934066  9.747253
27         신미불닭발-서울본점  4.882129  4.855513  9.737643
5          가마로강정-광흥창점  4.854545  4.872727  9.727273
31          이나닭강정-신촌점  4.897611  4.829352  9.726962
21       바른치킨-공덕파크자이점  4.857143  4.867347  9.724490
38       처갓집양념치킨-독립문점  4.837638  4.885609  9.723247
50            푸라닭-합정점  4.866667  4.855556  9.722222
17       마깐마포깐풍기-신촌본점  4.919118  4.797794  9.716912
2             BHC-신촌점  4.855219  4.855219  9.710438
9            교촌치킨-신촌점  4.815498  4.892989  9.708487
35         지코바치킨-독립문점  4.789298  4.889632  9.678930
24        순살만공격-마포신촌점  4.825939  4.836177  9.662116
33   전국3대치킨오성통닭-마포신촌점  4.800712  4.861210  9.661922
1             BHC-공덕점  4.807560  4.828179  9.635739
0             BBQ-신촌점  4.800000  4.744444  9.544444
52      호식이두마리치킨-명지대점  4.709898  4.802048  9.511945
25       숯미남숯불치킨에미친남자  4.709302  4.697674  9.406977

가게를 기준으로 총점을 기준으로 했을 때 상위 가게들이 대부분이 프랜차이즈임을 확인할 수 있다

2. 평점이 좋으면 리뷰도 좋은 리뷰만 있을까?

3. 양과 맛의 평점의 경우 동일할까? 아니면 양은 많은데 맛은 안 좋은 집이 있을까?

In [17]:
df[(df['맛']<=4) & (df['양']==5)]

,가게,맛,양,날짜,주문,사용자id,리뷰,총점,요일
67,후라이드참잘하는집-서강대점,2,5,2023-01-13,순살반반치킨（후라이드반＋,ch,치킨은 이상한맛났는데…,7,Friday
84,후라이드참잘하는집-서강대점,4,5,2022-12-31,순살 후라이드,ch,양이 많고 맛있었어용 !!!,9,Saturday
88,후라이드참잘하는집-서강대점,4,5,2022-12-30,반마리（순살）,ch,맛과 양이 좋습니다,9,Friday
181,후라이드참잘하는집-서강대점,4,5,2022-09-25,반마리（순살）,zl,맛있게 잘 먹었습니다~!!,9,Sunday
221,후라이드참잘하는집-서강대점,4,5,2022-09-07,반마리（순살）,ni,"자주 시켜먹는데, 순살은 처음시켜시켜보네요, 전 뼈있는 오리지널이 더 좋은듯 ㅎㅎ ...",9,Wednesday
...,...,...,...,...,...,...,...,...,...
13114,BHC-공덕점,4,5,2022-11-29,뿌링클（반）＋치즈볼,sk,1인분배달좋아요👍,9,Tuesday
13143,BHC-공덕점,1,5,2022-10-31,핫후라이드,hm,여기 핫후는 별로네요,6,Monday
13178,BHC-공덕점,4,5,2022-10-08,핫후라이드,hy,리뷰 치즈볼도 잘 먹었습니다ㅎㅎ 치킨 튀김이 단단하네요,9,Saturday
13368,치킨시대-명지대점,4,5,2022-01-06,안심순살텐더,ha,역시 맛과 양 둘다 좋습니다. 브랜드 치킨보다 푸짐하고 맛나요 또 주문할께요,9,Thursday
13379,치킨시대-명지대점,4,5,2021-12-16,크리스피치킨,im,맛있게 잘 먹었네요.,9,Thursday

In [18]:
df[(df['맛']==5) & (df['양']<=4)]

,가게,맛,양,날짜,주문,사용자id,리뷰,총점,요일
15,후라이드참잘하는집-서강대점,5,4,2023-02-11,반반치킨（후라이드반＋,ja,오랜만에 주문했는데 맛나게 먹었어요. 소스맛이 짱이네요^^,9,Saturday
57,후라이드참잘하는집-서강대점,5,3,2023-01-17,반마리（뼈）,ee,하... 이러시면 혼란해 혼란해..! 저 원래 튀김옷 별로 안 좋아하는데 후참잘로만...,8,Tuesday
125,후라이드참잘하는집-서강대점,5,4,2022-11-19,반반치킨（후라이드반＋매운,ma,알ㅇ이막 가이눔막 약긴익 태뱅닏능,9,Saturday
162,후라이드참잘하는집-서강대점,5,4,2022-10-10,허니버터치킨（무＋소스＋콜라）,cx,넘넘 맛있었어요! 허니버터맛이 처음에 먹어봤는데 또 먹고 싶고 양은 2인으로 먹으면...,9,Monday
174,후라이드참잘하는집-서강대점,5,4,2022-09-28,반마리（순살）,yu,안녕하세요 .. 이번주에만 3번 째 시킨 거 같은데 .. 정말 너무 맛있는데 어째 ...,9,Wednesday
...,...,...,...,...,...,...,...,...,...
13145,BHC-공덕점,5,4,2022-10-29,뿌링클（반）＋치즈볼,go,그 유명한 뿌링클치킨을 처음 먹어보았네요~위치가 초행길에 찾기 힘들었는데 가봤으니 ...,9,Saturday
13153,BHC-공덕점,5,4,2022-10-19,뿌링클순살,rl,넘모 맛있어여~~~,9,Wednesday
13168,BHC-공덕점,5,4,2022-10-10,후라이드,sh,후라이드 치킨의 최고봉~^^,9,Monday
13239,호치킨-마포래미안푸르지오점,5,4,2022-12-21,바베큐 로스트,ms,맛있게 잘먹었네요^^ 양이 조금 적어서 아쉬웠어요ㅜㅜ,9,Wednesday
13243,호치킨-마포래미안푸르지오점,5,4,2022-12-20,[시그니처]호차오,lu,"매콤한 향기에 정신없이 먹다보니 시간이 후다닥 지나갔네요. 아무래도, 다음 번에는 ...",9,Tuesday

맛의 평점과 양의 평점이 동일하지 않음을 확인할 수 있다.

4. 치킨을 언제 많이 시켜 먹을까? 불금에 치킨일까?

In [19]:
df['요일']=pd.to_datetime(df['날짜']).dt.day_name()
df['요일'].value_counts()

Sunday       2345
Saturday     2025
Monday       1788
Friday       1730
Tuesday      1600
Thursday     1595
Wednesday    1571
Name: 요일, dtype: int64

결과 : 일요일>토요일>월요일>금요일>화요일>목요일>수요일

의외로 일요일에 가장 많이 시켜먹는다는 것을 확인할 수 있었다.

5. 치킨집은 치느님이니 보정이 있을까?

In [21]:
print(len(df.loc[df['총점'] == 10]))
print(len(df.loc[df['총점'] == 9]))
print(len(df.loc[df['총점'] == 8]))
print(len(df.loc[df['총점'] == 7]))
print(len(df.loc[df['총점'] == 6]))
print(len(df.loc[df['총점'] == 5]))
print(len(df.loc[df['총점'] == 4]))
print(len(df.loc[df['총점'] == 3]))
print(len(df.loc[df['총점'] == 2]))

11491
506
348
97
91
31
34
8
48

In [22]:
df

,가게,맛,양,날짜,주문,사용자id,리뷰,총점,요일
0,후라이드참잘하는집-서강대점,5,5,2023-02-19,핫간장치킨（무＋소스＋콜라）,st,주문해놓고 샤워하고 나왔는데 바로 왔음 배달은 항상 빨라서 좋고 맛은 말할거 없이 ...,10,Sunday
1,후라이드참잘하는집-서강대점,5,5,2023-02-18,순살 후라이드,yh,맛있어요 너무 맛ㅇㅅ어옿,10,Saturday
2,후라이드참잘하는집-서강대점,5,5,2023-02-17,반마리（순살）,id,너무 맛있게 잘 먹렀어요. 머스터드 소스 넉넉히 주셔수 모자라지 않게 잘 먹었습니다.,10,Friday
3,후라이드참잘하는집-서강대점,5,5,2023-02-16,반마리（순살）,rl,굳굳굳 잘 먹었습니당,10,Thursday
4,후라이드참잘하는집-서강대점,5,5,2023-02-16,핫토스치킨（뼈）（무＋소스＋콜라）,st,시즈닝 팍팍~넘 맛있었요 간만에 치킨 먹은건데 기분좋게 먹었어요,10,Thursday
...,...,...,...,...,...,...,...,...,...
13375,치킨시대-명지대점,5,5,2021-12-24,원하는대로 삼총사（반／반／반）,ju,잘먹었습니다~~~!,10,Friday
13377,치킨시대-명지대점,5,5,2021-12-22,크리스피치킨,sn,맛있어요!튀김도맛있고,10,Wednesday
13378,치킨시대-명지대점,5,5,2021-12-18,원하는대로 삼총사（반／반／반）,ny,바삭바삭한 후라이드 크기부터 남달라요.~ 거기다 맛은 겉바삭 속은 매콤한게 완존 내...,10,Saturday
13379,치킨시대-명지대점,4,5,2021-12-16,크리스피치킨,im,맛있게 잘 먹었네요.,9,Thursday
13381,치킨시대-명지대점,5,5,2021-12-12,내맘대로 두마리세트,wk,양념 자극적이지 않고 치킨 속살 양념 잘 되어 있어서 간도 잘 맞아요 서비스로 주신...,10,Sunday

In [25]:
len(df['총점'])

12654

In [26]:
len(df.loc[df['총점'] == 10])/len(df['총점'])

0.9080923028291449

총점이 10점인 개수, 즉 맛과 양 모두 5점인 경우가 약 90%로 평점이 전체적으로 높다는 것을 알 수 있었다.